### PR TITLE
Custom 404 page

### PR DESCRIPTION
**Pull request by fedepad**

### CODE REVIEW

**Comment by fedepad** [comment]
For the 404 mentioned here: https://root.cern.ch/blog/624-and-2021/

**Comment by fedepad** [comment]
I pushed fixes for the html proofer checks so the checks need to be re-run.

**Comment by Axel-Naumann** [comment]
image

**Comment by Axel-Naumann** [comment]
image

**Comment by couet** [comment]
Thanks a lot for your contribution ! 
The 404 page is now in place. It should appear soon on the ROOT web site.
We will contact you soon for the promised reward.
Thanks again  for the great work you did !

The 404 page (soon online) is largely inspired from your contribution.

**Pull request closed without merging**
