### PR TITLE
executing a multi-line command did not reflect the reality

### PR DESCRIPTION
**Pull request by couet**

### CODE REVIEW

**Comment by ferdymercury** [comment]
I think the numbers between brackets don't need to be added, because earlier in the manual, it is said:

`For the further examples we will "abbreviate" root [0] etc by root [].`

**Review by ferdymercury — CHANGES_REQUESTED** [review]
Line 140 should be removed, too, I guess?

**Comment by couet** [comment]
oops sorry I metered ...

**Comment by ferdymercury** [comment]
It's really weird why this was there in the first place. I just tried with ROOT 5.34 and CINT, and the question marks don't work there, either... :

```
? TLine l;
Syntax Error: ? TLine l (tmpfile):1:
*** Interpreter error recovered ***

ROOT special commands.
===========================================================================
             pwd          : show current directory, pad and style
             ls           : list contents of current directory
             which [file] : shows path of macro file


```

**Pull request merged**
