### PR TITLE
enable httpproofer on push

### PR DESCRIPTION
**Pull request by stwunsch**
Enable the HTTP proofer on push to gh-pages

### CODE REVIEW

**Comment by stwunsch** [comment]
It's greeeeeen! :green_heart:

**Comment by stwunsch** [comment]
It seems that this would be ready for gh-pages. However, indico.desy.de seems to block the checks if we run too often :/ But just the assumption from the 403 error code.

**Comment by stwunsch** [comment]
Issues regarding indico.desy.de fixed in #224

**Comment by eguiraud** [comment]
Superseded by #227  ?

**Comment by stwunsch** [comment]
Yep, definitely

**Pull request closed without merging**
