### PR TITLE
Put "Under the Spotlight" under the spotlight

### PR DESCRIPTION
**Pull request by eguiraud**
Old:

old

New:

new

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
I'm not in love. I prefer an inconsistent font size that shows that this is front matter, rather than a small, body-style size.

**Comment by eguiraud** [comment]
The problem I'm trying to solve: blog post titles are currently so small that do not catch the eye at all.

Would you like me to try something else, or would you just leave it as it is?

**Comment by Axel-Naumann** [comment]
Thanks, I agree that's an issue. What about this:
- we merge tech blog and "under the spotlight" - as a use, why do I care about these two being separate? What makes something show up in one instead of the other?
- we remove the header "Under the Spotlight"
- the "under the spotlight" entry titles are sized to match the current "Under the Spotlight" header.

@couet thoughts (esp on separating "spotlight" and "tech blog")?

**Comment by couet** [comment]
The separation between "spotlight" and "tech blog" came from the old web site. I think "spotlight" was for the more recent posts ... that's it ... I agree they can be merged.

**Comment by eguiraud** [comment]
I will not have time to try out those changes before a while, so I converted this discussion to an issue, #362 . Closing this PR.

**Pull request closed without merging**
