### PR TITLE
As per Danilo's request: remove him from about/team

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by couet** [comment]
May be you should also remove the corresponding picture: /assets/images/DP.jpg

**Comment by couet** [comment]
And also, may be move him to: https://root.cern/about/previous_developers/

**Comment by eguiraud** [comment]
@couet thanks, did not remember we had that section. How about now?

**Comment by eguiraud** [comment]
...i'm guessing it's ok :D

**Pull request merged**
