### PR TITLE
update help message

### PR DESCRIPTION
**Pull request by ferdymercury**
according to https://github.com/root-project/root/issues/10065 and https://github.com/root-project/root/pull/10350

### CODE REVIEW

**Comment by ferdymercury** [comment]
It complements these other PRs whose merge is pending:
https://github.com/root-project/web/pull/775
https://github.com/root-project/web/pull/773

**Comment by ferdymercury** [comment]
@couet I think the failing check is unrelated to the PR ?

**Comment by couet** [comment]
It is weird because the two links mentioned by the HTML proofer seems correct:
https://github.com/root-project/web/runs/6106813603?check_suite_focus=true
I ran the build again and still the same error shows.
May be @eguiraud will have an idea.

**Comment by eguiraud** [comment]
@ferdymercury please rebase on the latest `main`, should be solved

**Comment by ferdymercury** [comment]
> @ferdymercury please rebase on the latest `main`, should be solved

done, thanks!

**Pull request merged**
