### PR TITLE
Add Snap package to /install

### PR DESCRIPTION
**Pull request by eguiraud**
@MrCarroll let me know if you would have anything to add. This will end up below https://root.cern/install#conda

### CODE REVIEW

**Comment by MrCarroll** [comment]
Most other ROOT installations have `thisroot.sh` or `conda activate` or similar to setup the `$PATH` properly. Since the Snap doesn't I think there's the possibility for confusion with users, particularly, snap usually appends to the end of $PATH and the other installs usually prepend to the front of $PATH, giving them them priority when invoked, and from what I see often people do this in their Bash login files.

I think there might be value in recommending people to use `which root` to ensure the environment is working as they expect, and possibly mention `snap run root-framework` as an explicit way to get the snap regardless of what has priority in the $PATH. If `which root` returns something with `/snap` in the string, you can probably assume it's actually working.

**Comment by eguiraud** [comment]
@MrCarroll is this better?

**Comment by eguiraud** [comment]
A preview of these changes is available at https://root.cern/484/install/#snap

**Comment by MrCarroll** [comment]
Looks good to me!

The `snap run` version has one specific advantage beyond being explicit, it also works in the event the user skipped rebooting the system when installing snapd, which would mean the snap binary is available but the snaps themselves aren't yet in $PATH, it rarely comes up, but inevitably it'll happen eventually so ;)

**Comment by eguiraud** [comment]
@couet @Axel-Naumann I'll merge later today if you don't have anything against it.

**Pull request merged**
