### PR TITLE
Build and deploy PRs to subdirectories on S3

### PR DESCRIPTION
**Pull request by eguiraud**

### CODE REVIEW

**Comment by stwunsch** [comment]
Could you also use the `--only-4xx` flag for the HTML proofer? -> https://github.com/root-project/web/pull/229

**Comment by stwunsch** [comment]
Once merge, please close https://github.com/root-project/web/pull/229 and https://github.com/root-project/web/pull/228

**Comment by Axel-Naumann** [comment]
> Looks all good to me! Though, is the infrastructure ready to publish the website for each PR?

The question is really: when can we delete the branch deployment from S3?

**Comment by eguiraud** [comment]
> is the infrastructure ready to publish the website for each PR?

yes?

> The question is really: when can we delete the branch deployment from S3?

Need another workflow triggered by PRs getting closed/merged

**Comment by stwunsch** [comment]
> > is the infrastructure ready to publish the website for each PR?
> 
> yes?
> 
> > The question is really: when can we delete the branch deployment from S3?
> 
> Need another workflow triggered by PRs getting closed/merged

I've just thought about limited uploads and such things. No idea what are the details there.

**Pull request merged**
