### PR TITLE
mention th1-long64

### PR DESCRIPTION
**Pull request by ferdymercury**
matching https://github.com/root-project/root/pull/8546/

### CODE REVIEW

**Comment by couet** [comment]
@ferdymercury . Now this PR has conflicts. Do you still want to keep it ? (sorry for the late check) > The primer has been revisited. You might rebase or create a new PR.

**Comment by ferdymercury** [comment]
Hi Olivier, I am happy to rebase. But do you think the MR https://github.com/root-project/root/pull/8546 will be merged any time soon? If not, then it's maybe better to wait here until it's clear whether it will be accepted or not into ROOT.

**Comment by couet** [comment]
Ah ... this PR is not under my control. May be ping the people in charge ?

**Comment by ferdymercury** [comment]
I've rebased this one :)

**Review by couet — APPROVED** [review]

**Comment by couet** [comment]
great ! so we wait for the other PR to be merged before merging this one?

**Comment by ferdymercury** [comment]
Thanks. I'd say so, we wait, as I am not sure whether the TH1L64 histogram will get incorporated into ROOT's main code anytime soon

**Comment by ferdymercury** [comment]
Hi Axel, are you sure this should have been merged? The code has not yeen been added, see  https://github.com/root-project/root/pull/8546

**Comment by Axel-Naumann** [comment]
Argh sorry. I'll revert!

**Pull request merged**
