### PR TITLE
Add favicons

### PR DESCRIPTION
**Pull request by stwunsch**
- Replace favicon.ico in the toplevel dir with the same as for the forum
  with transparent background
- Add to the header of each page the modern way to include favicons in 3
  size (ico files are kind of deprecated, though kept due to backwards
  compatibility)

The path points to the location for the current structure and has to be adapted once we move the deployment to a setup without the `/web` prefix.

### CODE REVIEW

**Comment by eguiraud** [comment]
I think we will always deploy into a `/web` directory, only difference will be that we put a reverse proxy in front, but it should be fine to assume we deploy in `/web`

**Comment by Axel-Naumann** [comment]
The reverse proxy will make this accessible as `/`, not `/web` - not sure whether we need anything here?

**Comment by Axel-Naumann** [comment]
But the png-s are a good idea either way!

**Comment by eguiraud** [comment]
> The reverse proxy will make this accessible as `/`, not `/web` - not sure whether we need anything here?

access to the favicon should also be reverse-proxied. i expect all content available under `/web` to be served from `/` by the reverse proxy, and just work. if I'm wrong, i'll fix it.

**Comment by stwunsch** [comment]
I would also just put this in for now, keep the issue open and fix the path for the finally deployed version.

**Comment by eguiraud** [comment]
Let's merge -- if changing the URL breaks the favicons I'll fix the URLs they are available from

**Pull request merged**
