### PR TITLE
Add link checker workflow

### PR DESCRIPTION
**Pull request by stwunsch**

### CODE REVIEW

**Comment by eguiraud** [comment]
there won't be a _site directory until jekyll builds the website right?

it would make sense, for PRs, to build the website and check links, and for the gh-pages branch to build the website, check links and deploy. I am not sure how to disable the deploy step for PRs

**Comment by stwunsch** [comment]
I guess the jekyll actions builds the website, right?

**Comment by eguiraud** [comment]
ok you do it with `job.jobname.if`: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

So I think this link checker action should be part of the main workflow (which should run for PRs too), a step before the copy to S3, and the copy to S3 should be performed only `if github.ref == 'gh-pages'`

What do you think?

**Comment by eguiraud** [comment]
> I guess the jekyll actions builds the website, right?

yes, if it's part of the workflow :D

**Comment by stwunsch** [comment]
> > I guess the jekyll actions builds the website, right?
> 
> yes, if it's part of the workflow :D

I think i fixed it :D

**Comment by eguiraud** [comment]
the jekyll action builds the website in `/build`, not `_site` :D

**Comment by stwunsch** [comment]
Also figured this out in the meanwhile :D Now I've to figure out the actual path to `build/`. Incremental steps ;)

**Comment by stwunsch** [comment]
We are using HTML proofer instead.

**Pull request closed without merging**
