### PR TITLE
bump cxx default standard to 14, root7 to 17

### PR DESCRIPTION
**Pull request by ferdymercury**
Fixes https://github.com/root-project/web/issues/636

### CODE REVIEW

**Comment by couet** [comment]
I think @eguiraud  was the author of this page (if I am right) . 
He will know if these changes are valid or not.

**Review by eguiraud — APPROVED** [review]
looks good, thank you very much @ferdymercury

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
Is this superseded by https://github.com/ferdymercury/web/pull/1 and can be closed?

**Comment by ferdymercury** [comment]
(No, that was a merge of egirauds fork into my fork)

**Pull request merged**
