### PR TITLE
Link to extra Genvector doc

### PR DESCRIPTION
**Pull request by couet**
Link to extra Genvector doc in topical manuals

### CODE REVIEW

**Comment by couet** [comment]
We have a problem with the PR. The link to the pdf is "http" and the root web site accept only "https". @lmoneta do you think you can put this pdf on our server ?

**Comment by lmoneta** [comment]
Hi Olivier, 

Yes you should put the pdf in the root.cern.ch server. I am not sure how log seal.cern.ch will be still valid.
Thank you for doing this

Lorenzo

**Review by JohannesHentrich — APPROVED** [review]
Very good. Thank you for doing this !

**Comment by couet** [comment]
Hi Lorenzo,

You do not need to log in to seal. It is a pdf file. It is enough to download it from the browser. Here it is:
[GenVector.pdf](https://github.com/root-project/web/files/5353908/GenVector.pdf)
Now I do not know how to put it on root.cern.ch file server.

Cheers,
Oilvier

**Comment by lmoneta** [comment]
I don't have access. But you can add the file also on git (root git or the root web git)

Lorenzo

**Comment by couet** [comment]
Ok done. the pdf file is in the "topical" folder

**Pull request merged**
