### PR TITLE
remove broken link

### PR DESCRIPTION
**Pull request by ferdymercury**
6.24 does not have qch file

### CODE REVIEW

**Review by couet — APPROVED** [review]

**Comment by couet** [comment]
There is an error: https://github.com/root-project/web/runs/5406161326?check_suite_focus=true

**Comment by ferdymercury** [comment]
That error seems to come from a page I didn't modify: ./build/758/get_started/courses/index.html

**Comment by couet** [comment]
It is weird because the link to "columbia" is valid... I re-launched it to see if it was temporary unavailable

**Comment by couet** [comment]
Ok it passed

**Pull request merged**
