### PR TITLE
fix relative links of the icons

### PR DESCRIPTION
**Pull request by stwunsch**
The additional ticks are required to make the link work!

### CODE REVIEW

**Comment by stwunsch** [comment]
An external link is unresponsive with error code 503 :/ Probably we should enable that we fail only on 40x error codes?

**Comment by stwunsch** [comment]
Screenshot from 2020-06-19 08-17-21

**Comment by stwunsch** [comment]
Fixed by https://github.com/root-project/web/pull/227, the PR here can just be closed once the other one is merged. I"ll keep it open for now because the links of the icons are crucial.

**Comment by eguiraud** [comment]
Fixed in #227

**Pull request closed without merging**
