### PR TITLE
Initial page for documenting GH Actions CI.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
@olemorud FYI, please add to this!

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@olemorud you can soon (once GH actions are done) see a snapshot at https://root.cern/855/

**Comment by Axel-Naumann** [comment]
It's here: https://root.cern/855/for_developers/continuous_integration-testing/githubactions/

**Comment by olemorud** [comment]
Nice, thanks!

**Review by Axel-Naumann — COMMENTED** [review]
That's amazing, @olemorud - thank you so much!

**Pull request merged**
