### PR TITLE
prefer builtin afterimage

### PR DESCRIPTION
**Pull request by ferdymercury**
Only to be merged after https://github.com/root-project/root/pull/14395 or https://github.com/root-project/root/pull/14396

### CODE REVIEW

**Review by couet — APPROVED** [review]
I am not expert in the installlation scripts but as far as I understand it it looks ok for me.

**Comment by ferdymercury** [comment]
Now that the depending MR was merged, I think this could be merged, too. (Unless you prefer to wait for 6.30.04)

**Comment by ferdymercury** [comment]
pinging @couet as 6.30.04 is already out
thanks!

**Comment by ferdymercury** [comment]
Thanks!!
Btw https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/3242/console seems to be hanging.

**Pull request merged**
